; Listing generated by Microsoft (R) Optimizing Compiler Version 19.23.28106.4 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
$SG114932 DB	'C:\QT\5.12.5\MSVC2017_64\include\QtCore\qmetatype.h', 00H
$SG116098 DB	'%s', 00H
	ORG $+9
$SG114933 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG114934 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG115748 DB	'C:\QT\5.12.5\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG115749 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG115750 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG116097 DB	'invalid argument', 00H
	ORG $+15
$SG116099 DB	'C:\Program Files (x86)\Microsoft Visual Studio\2019\Comm'
	DB	'unity\VC\Tools\MSVC\14.23.28105\include\xmemory', 00H
	ORG $+8
$SG116100 DB	'C', 00H, ':', 00H, '\', 00H, 'P', 00H, 'r', 00H, 'o', 00H
	DB	'g', 00H, 'r', 00H, 'a', 00H, 'm', 00H, ' ', 00H, 'F', 00H, 'i'
	DB	00H, 'l', 00H, 'e', 00H, 's', 00H, ' ', 00H, '(', 00H, 'x', 00H
	DB	'8', 00H, '6', 00H, ')', 00H, '\', 00H, 'M', 00H, 'i', 00H, 'c'
	DB	00H, 'r', 00H, 'o', 00H, 's', 00H, 'o', 00H, 'f', 00H, 't', 00H
	DB	' ', 00H, 'V', 00H, 'i', 00H, 's', 00H, 'u', 00H, 'a', 00H, 'l'
	DB	00H, ' ', 00H, 'S', 00H, 't', 00H, 'u', 00H, 'd', 00H, 'i', 00H
	DB	'o', 00H, '\', 00H, '2', 00H, '0', 00H, '1', 00H, '9', 00H, '\'
	DB	00H, 'C', 00H, 'o', 00H, 'm', 00H, 'm', 00H, 'u', 00H, 'n', 00H
	DB	'i', 00H, 't', 00H, 'y', 00H, '\', 00H, 'V', 00H, 'C', 00H, '\'
	DB	00H, 'T', 00H, 'o', 00H, 'o', 00H, 'l', 00H, 's', 00H, '\', 00H
	DB	'M', 00H, 'S', 00H, 'V', 00H, 'C', 00H, '\', 00H, '1', 00H, '4'
	DB	00H, '.', 00H, '2', 00H, '3', 00H, '.', 00H, '2', 00H, '8', 00H
	DB	'1', 00H, '0', 00H, '5', 00H, '\', 00H, 'i', 00H, 'n', 00H, 'c'
	DB	00H, 'l', 00H, 'u', 00H, 'd', 00H, 'e', 00H, '\', 00H, 'x', 00H
	DB	'm', 00H, 'e', 00H, 'm', 00H, 'o', 00H, 'r', 00H, 'y', 00H, 00H
	DB	00H
$SG116101 DB	's', 00H, 't', 00H, 'd', 00H, ':', 00H, ':', 00H, '_', 00H
	DB	'A', 00H, 'l', 00H, 'l', 00H, 'o', 00H, 'c', 00H, 'a', 00H, 't'
	DB	00H, 'e', 00H, '_', 00H, 'm', 00H, 'a', 00H, 'n', 00H, 'u', 00H
	DB	'a', 00H, 'l', 00H, 'l', 00H, 'y', 00H, '_', 00H, 'v', 00H, 'e'
	DB	00H, 'c', 00H, 't', 00H, 'o', 00H, 'r', 00H, '_', 00H, 'a', 00H
	DB	'l', 00H, 'i', 00H, 'g', 00H, 'n', 00H, 'e', 00H, 'd', 00H, 00H
	DB	00H
	ORG $+2
$SG116102 DB	'"', 00H, 'i', 00H, 'n', 00H, 'v', 00H, 'a', 00H, 'l', 00H
	DB	'i', 00H, 'd', 00H, ' ', 00H, 'a', 00H, 'r', 00H, 'g', 00H, 'u'
	DB	00H, 'm', 00H, 'e', 00H, 'n', 00H, 't', 00H, '"', 00H, 00H, 00H
	ORG $+10
$SG116206 DB	'C:\Program Files (x86)\Microsoft Visual Studio\2019\Comm'
	DB	'unity\VC\Tools\MSVC\14.23.28105\include\xlocale', 00H
	ORG $+8
?qt_meta_stringdata_PolylineModel@@3Uqt_meta_stringdata_PolylineModel_t@@B DD 0ffffffffH ; qt_meta_stringdata_PolylineModel
	DD	0dH
	DD	00H
	ORG $+4
	DQ	0000000000000078H
	DD	0ffffffffH
	DD	0aH
	DD	00H
	ORG $+4
	DQ	000000000000006eH
	DD	0ffffffffH
	DD	00H
	DD	00H
	ORG $+4
	DQ	0000000000000061H
	DD	0ffffffffH
	DD	09H
	DD	00H
	ORG $+4
	DQ	000000000000004aH
	DD	0ffffffffH
	DD	03H
	DD	00H
	ORG $+4
	DQ	000000000000003cH
	DB	050H
	DB	06fH
	DB	06cH
	DB	079H
	DB	06cH
	DB	069H
	DB	06eH
	DB	065H
	DB	04dH
	DB	06fH
	DB	064H
	DB	065H
	DB	06cH
	DB	00H
	DB	074H
	DB	072H
	DB	061H
	DB	063H
	DB	06bH
	DB	073H
	DB	053H
	DB	069H
	DB	07aH
	DB	065H
	DB	00H
	DB	00H
	DB	074H
	DB	072H
	DB	061H
	DB	063H
	DB	06bH
	DB	044H
	DB	061H
	DB	074H
	DB	061H
	DB	00H
	DB	069H
	DB	064H
	DB	078H
	DB	00H
?qt_meta_data_PolylineModel@@3QBIB DD 08H		; qt_meta_data_PolylineModel
	DD	00H
	DD	00H
	DD	00H
	DD	02H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	018H
	DD	02H
	DD	02H
	DD	03H
	DD	01H
	DD	019H
	DD	02H
	DD	02H
	DD	02H
	DD	029H
	DD	02H
	DD	04H
	DD	00H
	ORG $+4
$SG111676 DB	'C:\QT\5.12.5\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+4
$SG111677 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG111678 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG114278 DB	'C:\QT\5.12.5\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG114279 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG114280 DB	'qRegisterNormalizedMetaType', 00H
	ORG $+4
$SG114605 DB	'C:\QT\5.12.5\MSVC2017_64\include\QtCore\qmetatype.h', 00H
	ORG $+12
$SG114606 DB	'qRegisterNormalizedMetaType was called with a not normal'
	DB	'ized type name, please call qRegisterMetaType instead.', 00H
	ORG $+1
$SG114607 DB	'qRegisterNormalizedMetaType', 00H
CONST	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
PUBLIC	?metaObject@PolylineModel@@UEBAPEBUQMetaObject@@XZ ; PolylineModel::metaObject
PUBLIC	?qt_metacast@PolylineModel@@UEAAPEAXPEBD@Z	; PolylineModel::qt_metacast
PUBLIC	?qt_metacall@PolylineModel@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ; PolylineModel::qt_metacall
PUBLIC	?qt_static_metacall@PolylineModel@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; PolylineModel::qt_static_metacall
PUBLIC	??$move@AEAH@std@@YA$$QEAHAEAH@Z		; std::move<int &>
PUBLIC	??$move@AEAVQVariant@@@std@@YA$$QEAVQVariant@@AEAV1@@Z ; std::move<QVariant &>
PUBLIC	?staticMetaObject@PolylineModel@@2UQMetaObject@@B ; PolylineModel::staticMetaObject
EXTRN	strcmp:PROC
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ:PROC
EXTRN	__imp_??1QVariant@@QEAA@XZ:PROC
EXTRN	__imp_??4QVariant@@QEAAAEAV0@$$QEAV0@@Z:PROC
EXTRN	__imp_?qt_metacast@QAbstractListModel@@UEAAPEAXPEBD@Z:PROC
EXTRN	__imp_?qt_metacall@QAbstractListModel@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z:PROC
EXTRN	?tracksSize@PolylineModel@@QEBAHXZ:PROC		; PolylineModel::tracksSize
EXTRN	?trackData@PolylineModel@@QEBA?AVQVariant@@H@Z:PROC ; PolylineModel::trackData
EXTRN	__imp_?staticMetaObject@QAbstractListModel@@2UQMetaObject@@B:BYTE
_BSS	SEGMENT
?staticMetaObject@PolylineModel@@2UQMetaObject@@B DB 030H DUP (?) ; PolylineModel::staticMetaObject
_BSS	ENDS
pdata	SEGMENT
$pdata$?metaObject@PolylineModel@@UEBAPEBUQMetaObject@@XZ DD imagerel $LN5
	DD	imagerel $LN5+88
	DD	imagerel $unwind$?metaObject@PolylineModel@@UEBAPEBUQMetaObject@@XZ
$pdata$?qt_metacast@PolylineModel@@UEAAPEAXPEBD@Z DD imagerel $LN5
	DD	imagerel $LN5+75
	DD	imagerel $unwind$?qt_metacast@PolylineModel@@UEAAPEAXPEBD@Z
$pdata$?qt_metacall@PolylineModel@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN9
	DD	imagerel $LN9+174
	DD	imagerel $unwind$?qt_metacall@PolylineModel@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
$pdata$?qt_static_metacall@PolylineModel@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD imagerel $LN12
	DD	imagerel $LN12+250
	DD	imagerel $unwind$?qt_static_metacall@PolylineModel@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z
pdata	ENDS
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@PolylineModel@@2P6AXXZEA@@3P6AXXZEA DQ FLAT:??__E?staticMetaObject@PolylineModel@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@PolylineModel@@2P6AXXZEA@@3P6AXXZEA
CRT$XCU	ENDS
xdata	SEGMENT
$unwind$?metaObject@PolylineModel@@UEBAPEBUQMetaObject@@XZ DD 010901H
	DD	06209H
$unwind$?qt_metacast@PolylineModel@@UEAAPEAXPEBD@Z DD 010e01H
	DD	0420eH
$unwind$?qt_metacall@PolylineModel@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	04217H
$unwind$?qt_static_metacall@PolylineModel@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z DD 011701H
	DD	08217H
xdata	ENDS
; Function compile flags: /Odtp
;	COMDAT ??__E?staticMetaObject@PolylineModel@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@PolylineModel@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'PolylineModel::staticMetaObject'', COMDAT
; File C:\source\sds\map_canvas\Debug\moc_PolylineModel.cpp
; Line 86
	mov	rax, QWORD PTR __imp_?staticMetaObject@QAbstractListModel@@2UQMetaObject@@B
	mov	QWORD PTR ?staticMetaObject@PolylineModel@@2UQMetaObject@@B, rax
; Line 87
	lea	rax, OFFSET FLAT:?qt_meta_stringdata_PolylineModel@@3Uqt_meta_stringdata_PolylineModel_t@@B
	mov	QWORD PTR ?staticMetaObject@PolylineModel@@2UQMetaObject@@B+8, rax
; Line 88
	lea	rax, OFFSET FLAT:?qt_meta_data_PolylineModel@@3QBIB
	mov	QWORD PTR ?staticMetaObject@PolylineModel@@2UQMetaObject@@B+16, rax
; Line 89
	lea	rax, OFFSET FLAT:?qt_static_metacall@PolylineModel@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; PolylineModel::qt_static_metacall
	mov	QWORD PTR ?staticMetaObject@PolylineModel@@2UQMetaObject@@B+24, rax
; Line 90
	mov	QWORD PTR ?staticMetaObject@PolylineModel@@2UQMetaObject@@B+32, 0
; Line 91
	mov	QWORD PTR ?staticMetaObject@PolylineModel@@2UQMetaObject@@B+40, 0
	ret	0
??__E?staticMetaObject@PolylineModel@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'PolylineModel::staticMetaObject''
text$di	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$move@AEAVQVariant@@@std@@YA$$QEAVQVariant@@AEAV1@@Z
_TEXT	SEGMENT
_Arg$ = 8
??$move@AEAVQVariant@@@std@@YA$$QEAVQVariant@@AEAV1@@Z PROC ; std::move<QVariant &>, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\type_traits
; Line 1432
	mov	QWORD PTR [rsp+8], rcx
; Line 1433
	mov	rax, QWORD PTR _Arg$[rsp]
; Line 1434
	ret	0
??$move@AEAVQVariant@@@std@@YA$$QEAVQVariant@@AEAV1@@Z ENDP ; std::move<QVariant &>
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??$move@AEAH@std@@YA$$QEAHAEAH@Z
_TEXT	SEGMENT
_Arg$ = 8
??$move@AEAH@std@@YA$$QEAHAEAH@Z PROC			; std::move<int &>, COMDAT
; File C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\type_traits
; Line 1432
	mov	QWORD PTR [rsp+8], rcx
; Line 1433
	mov	rax, QWORD PTR _Arg$[rsp]
; Line 1434
	ret	0
??$move@AEAH@std@@YA$$QEAHAEAH@Z ENDP			; std::move<int &>
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv69 = 32
_r$1 = 36
_t$2 = 40
_r$3 = 48
_o$ = 80
_c$ = 88
_id$ = 96
_a$ = 104
?qt_static_metacall@PolylineModel@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z PROC ; PolylineModel::qt_static_metacall
; File C:\source\sds\map_canvas\Debug\moc_PolylineModel.cpp
; Line 71
$LN12:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H
; Line 72
	cmp	DWORD PTR _c$[rsp], 0
	jne	$LN4@qt_static_
; Line 73
	mov	rax, QWORD PTR _o$[rsp]
	mov	QWORD PTR _t$2[rsp], rax
; Line 75
	mov	eax, DWORD PTR _id$[rsp]
	mov	DWORD PTR tv69[rsp], eax
	cmp	DWORD PTR tv69[rsp], 0
	je	SHORT $LN5@qt_static_
	cmp	DWORD PTR tv69[rsp], 1
	je	SHORT $LN7@qt_static_
	jmp	$LN4@qt_static_
$LN5@qt_static_:
; Line 76
	mov	rcx, QWORD PTR _t$2[rsp]
	call	?tracksSize@PolylineModel@@QEBAHXZ	; PolylineModel::tracksSize
	mov	DWORD PTR _r$1[rsp], eax
; Line 77
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	cmp	QWORD PTR [rcx+rax], 0
	je	SHORT $LN6@qt_static_
	lea	rcx, QWORD PTR _r$1[rsp]
	call	??$move@AEAH@std@@YA$$QEAHAEAH@Z	; std::move<int &>
	mov	ecx, 8
	imul	rcx, rcx, 0
	mov	rdx, QWORD PTR _a$[rsp]
	mov	rcx, QWORD PTR [rdx+rcx]
	mov	eax, DWORD PTR [rax]
	mov	DWORD PTR [rcx], eax
$LN6@qt_static_:
	jmp	SHORT $LN4@qt_static_
$LN7@qt_static_:
; Line 78
	mov	eax, 8
	imul	rax, rax, 1
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	r8d, DWORD PTR [rax]
	lea	rdx, QWORD PTR _r$3[rsp]
	mov	rcx, QWORD PTR _t$2[rsp]
	call	?trackData@PolylineModel@@QEBA?AVQVariant@@H@Z ; PolylineModel::trackData
; Line 79
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	cmp	QWORD PTR [rcx+rax], 0
	je	SHORT $LN8@qt_static_
	lea	rcx, QWORD PTR _r$3[rsp]
	call	??$move@AEAVQVariant@@@std@@YA$$QEAVQVariant@@AEAV1@@Z ; std::move<QVariant &>
	mov	ecx, 8
	imul	rcx, rcx, 0
	mov	rdx, rax
	mov	rax, QWORD PTR _a$[rsp]
	mov	rcx, QWORD PTR [rax+rcx]
	call	QWORD PTR __imp_??4QVariant@@QEAAAEAV0@$$QEAV0@@Z
$LN8@qt_static_:
	lea	rcx, QWORD PTR _r$3[rsp]
	call	QWORD PTR __imp_??1QVariant@@QEAA@XZ
$LN4@qt_static_:
; Line 83
	add	rsp, 72					; 00000048H
	ret	0
?qt_static_metacall@PolylineModel@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ENDP ; PolylineModel::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_c$ = 56
_id$ = 64
_a$ = 72
?qt_metacall@PolylineModel@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z PROC ; PolylineModel::qt_metacall
; File C:\source\sds\map_canvas\Debug\moc_PolylineModel.cpp
; Line 109
$LN9:
	mov	QWORD PTR [rsp+32], r9
	mov	DWORD PTR [rsp+24], r8d
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 110
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacall@QAbstractListModel@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z
	mov	DWORD PTR _id$[rsp], eax
; Line 111
	cmp	DWORD PTR _id$[rsp], 0
	jge	SHORT $LN2@qt_metacal
; Line 112
	mov	eax, DWORD PTR _id$[rsp]
	jmp	SHORT $LN1@qt_metacal
$LN2@qt_metacal:
; Line 113
	cmp	DWORD PTR _c$[rsp], 0
	jne	SHORT $LN3@qt_metacal
; Line 114
	cmp	DWORD PTR _id$[rsp], 2
	jge	SHORT $LN5@qt_metacal
; Line 115
	mov	r9, QWORD PTR _a$[rsp]
	mov	r8d, DWORD PTR _id$[rsp]
	mov	edx, DWORD PTR _c$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	?qt_static_metacall@PolylineModel@@CAXPEAVQObject@@W4Call@QMetaObject@@HPEAPEAX@Z ; PolylineModel::qt_static_metacall
$LN5@qt_metacal:
; Line 116
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 2
	mov	DWORD PTR _id$[rsp], eax
	jmp	SHORT $LN4@qt_metacal
$LN3@qt_metacal:
; Line 117
	cmp	DWORD PTR _c$[rsp], 12
	jne	SHORT $LN6@qt_metacal
; Line 118
	cmp	DWORD PTR _id$[rsp], 2
	jge	SHORT $LN7@qt_metacal
; Line 119
	mov	eax, 8
	imul	rax, rax, 0
	mov	rcx, QWORD PTR _a$[rsp]
	mov	rax, QWORD PTR [rcx+rax]
	mov	DWORD PTR [rax], -1
$LN7@qt_metacal:
; Line 120
	mov	eax, DWORD PTR _id$[rsp]
	sub	eax, 2
	mov	DWORD PTR _id$[rsp], eax
$LN6@qt_metacal:
$LN4@qt_metacal:
; Line 122
	mov	eax, DWORD PTR _id$[rsp]
$LN1@qt_metacal:
; Line 123
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacall@PolylineModel@@UEAAHW4Call@QMetaObject@@HPEAPEAX@Z ENDP ; PolylineModel::qt_metacall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
this$ = 48
_clname$ = 56
?qt_metacast@PolylineModel@@UEAAPEAXPEBD@Z PROC		; PolylineModel::qt_metacast
; File C:\source\sds\map_canvas\Debug\moc_PolylineModel.cpp
; Line 101
$LN5:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
; Line 102
	cmp	QWORD PTR _clname$[rsp], 0
	jne	SHORT $LN2@qt_metacas
	xor	eax, eax
	jmp	SHORT $LN1@qt_metacas
$LN2@qt_metacas:
; Line 103
	lea	rdx, OFFSET FLAT:?qt_meta_stringdata_PolylineModel@@3Uqt_meta_stringdata_PolylineModel_t@@B+120
	mov	rcx, QWORD PTR _clname$[rsp]
	call	strcmp
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 104
	mov	rax, QWORD PTR this$[rsp]
	jmp	SHORT $LN1@qt_metacas
$LN3@qt_metacas:
; Line 105
	mov	rdx, QWORD PTR _clname$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	QWORD PTR __imp_?qt_metacast@QAbstractListModel@@UEAAPEAXPEBD@Z
$LN1@qt_metacas:
; Line 106
	add	rsp, 40					; 00000028H
	ret	0
?qt_metacast@PolylineModel@@UEAAPEAXPEBD@Z ENDP		; PolylineModel::qt_metacast
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
tv82 = 32
this$ = 64
?metaObject@PolylineModel@@UEBAPEBUQMetaObject@@XZ PROC	; PolylineModel::metaObject
; File C:\source\sds\map_canvas\Debug\moc_PolylineModel.cpp
; Line 96
$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H
; Line 97
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	cmp	QWORD PTR [rax+40], 0
	je	SHORT $LN3@metaObject
	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
	mov	rcx, rax
	call	QWORD PTR __imp_?dynamicMetaObject@QObjectData@@QEBAPEAUQMetaObject@@XZ
	mov	QWORD PTR tv82[rsp], rax
	jmp	SHORT $LN4@metaObject
$LN3@metaObject:
	lea	rax, OFFSET FLAT:?staticMetaObject@PolylineModel@@2UQMetaObject@@B ; PolylineModel::staticMetaObject
	mov	QWORD PTR tv82[rsp], rax
$LN4@metaObject:
	mov	rax, QWORD PTR tv82[rsp]
; Line 98
	add	rsp, 56					; 00000038H
	ret	0
?metaObject@PolylineModel@@UEBAPEBUQMetaObject@@XZ ENDP	; PolylineModel::metaObject
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ
_TEXT	SEGMENT
this$ = 8
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; File C:\QT\5.12.5\MSVC2017_64\include\QtCore\qscopedpointer.h
; Line 117
	mov	QWORD PTR [rsp+8], rcx
; Line 118
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QEBAPEAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File C:\source\sds\map_canvas\Debug\moc_PolylineModel.cpp
; Line 126
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File C:\source\sds\map_canvas\Debug\moc_PolylineModel.cpp
; Line 126
	mov	QWORD PTR [rsp+8], rcx
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
